/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.DefaultListModel;
import models.Person;

/**
 *
 * @author jahood
 */
public class Manage_Cards extends javax.swing.JFrame {
    
    public class Node
    {
        int value;
        Node leftNode;
        Node rightNode;
        
        public Node(int valueIn)
        {
            value = valueIn;
            leftNode = null;
            rightNode = null;
        }
    }
    
    public class BinarySearchTree
    {
        Node root;
        
        public BinarySearchTree()
        {
            root = null;
        }
        
        public void insert(int value)
        {
            root = insert(root, value);
        }
        
        public Node insert(Node node, int value)
        {
            if (node == null)
            {
                return new Node(value);
            }
            if(value < node.value)
            {
                node.leftNode = insert(node.leftNode, value);
            }
            else if(value > node.value)
            {
                node.rightNode = insert(node.rightNode, value);
            }
            return node;
        }
        
        
        public void delete(int value) {
            root = delete(root, value);
        }


        public Node delete(Node root, int value) {
            if (root == null) {
                return null;
            }

            if (value < root.value) {
                root.leftNode = delete(root.leftNode, value);
            } else if (value > root.value) {
                root.rightNode = delete(root.rightNode, value);
            } else {
                // Node with only one child or no child
                if (root.leftNode == null)
                {
                    return root.rightNode;
                }
                else if (root.rightNode == null)
                {
                    return root.leftNode;
                }

                // Node with two children: get the in-order successor (smallest in the right subtree)
                root.value = minValue(root.rightNode);

                // Delete the in-order successor
                root.rightNode = delete(root.rightNode, root.value);
            }

            return root;
        }

        private int minValue(Node node) {
            int minv = node.value;
            while (node.leftNode != null) {
                minv = node.leftNode.value;
                node = node.leftNode;
            }
            return minv;
        }

    }

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Manage_Cards.class.getName());
    
    private Person loggedInPerson;
    private BinarySearchTree BST;
    

    /**
     * Creates new form Manage_Cards
     */
    public Manage_Cards(Person p) {
        initComponents();
        
        loggedInPerson = p;
        BST = load_cards_into_BST();
        
        DefaultListModel cards = new DefaultListModel();
        display_in_order(cards, BST.root);
        lstCards.setModel(cards);

    }
       
    public void display_in_order(DefaultListModel cards, Node node)
    {
        
        if(node != null)
        {
            display_in_order(cards, node.leftNode);
            cards.addElement(String.valueOf(node.value)); 
            display_in_order(cards, node.rightNode);
        }
        
    }
    
    public BinarySearchTree load_cards_into_BST()
    {
        String card1 = "764";
        String card2 = "202";
        String card22 = "101";
        String card3 = "404";
        String card4 = "384";
        String card5 = "830";
        
        loggedInPerson.addCard(card1);
        loggedInPerson.addCard(card2);
        loggedInPerson.addCard(card22);
        loggedInPerson.addCard(card3);
        loggedInPerson.addCard(card4);
        loggedInPerson.addCard(card5);
        
        BinarySearchTree BST = new BinarySearchTree();
        for(String card : loggedInPerson.get_Cards())
        {
            BST.insert(Integer.parseInt(card));
        }
        
        return BST;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCards = new javax.swing.JList<>();
        txtNewCard = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSaveCard = new javax.swing.JButton();
        btnRemoveCard = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lstCards);

        jLabel1.setText("Save New Card:");

        btnSaveCard.setText("Save Card");
        btnSaveCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCardActionPerformed(evt);
            }
        });

        btnRemoveCard.setText("Remove Select Card");
        btnRemoveCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCardActionPerformed(evt);
            }
        });

        jLabel2.setText("BRAND NEW");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoveCard)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtNewCard, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveCard)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveCard))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRemoveCard)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCardActionPerformed
       
        int newCardNumber = Integer.parseInt(txtNewCard.getText());       
        BST.insert(newCardNumber);
        
        DefaultListModel cards = new DefaultListModel();
        display_in_order(cards, BST.root);
        lstCards.setModel(cards);
        
    }//GEN-LAST:event_btnSaveCardActionPerformed

    private void btnRemoveCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCardActionPerformed
        
        int cardNo = Integer.parseInt(lstCards.getSelectedValue());
        BST.delete(cardNo);
        
        DefaultListModel cards = new DefaultListModel();
        display_in_order(cards, BST.root);
        lstCards.setModel(cards);
        
    }//GEN-LAST:event_btnRemoveCardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Manage_Cards(new Person()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoveCard;
    private javax.swing.JButton btnSaveCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstCards;
    private javax.swing.JTextField txtNewCard;
    // End of variables declaration//GEN-END:variables
}
