/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

import javax.swing.DefaultListModel;
import models.Person;

/**
 *
 * @author jahood
 */
public class Select_Card extends javax.swing.JFrame {

    private Person loggedInPerson;
    
    /**
     * Creates new form Select_Card
     */
    public Select_Card(Person p) {

        initComponents();
        
        loggedInPerson = p;
        load_cards();
        refresh_cards();
        
    }
    
    public void refresh_cards()
    {
        DefaultListModel cards = new DefaultListModel();
        for (int i = 0; i < loggedInPerson.get_Cards().size(); i++) { 
            cards.addElement(loggedInPerson.get_Cards().get(i));
        }
        
        lstCards.setModel(cards);

    }
    
    public void load_cards()
    {
        String card1 = "123";
        String card2 = "456";
        String card3 = "789";
        
        loggedInPerson.addCard(card1);
        loggedInPerson.addCard(card2);
        loggedInPerson.addCard(card3);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUseCard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCards = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        txtNewCardNo = new javax.swing.JTextField();
        btnAddCard = new javax.swing.JButton();
        lblNewCard = new javax.swing.JLabel();
        lblConfirmation = new javax.swing.JLabel();
        btnRemoveCard = new javax.swing.JButton();
        lblRemoveCard = new javax.swing.JLabel();
        btnSaveFirst = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUseCard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUseCard.setText("Use Card");
        btnUseCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUseCardActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Card:");

        jScrollPane1.setViewportView(lstCards);

        jLabel2.setText("Enter New Card Number:");

        btnAddCard.setText("Add Card");
        btnAddCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCardActionPerformed(evt);
            }
        });

        lblConfirmation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnRemoveCard.setText("Remove Card");
        btnRemoveCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCardActionPerformed(evt);
            }
        });

        btnSaveFirst.setText("Save as Default Payment Method");
        btnSaveFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveFirstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRemoveCard)
                    .addComponent(btnRemoveCard)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(btnUseCard)
                            .addComponent(btnSaveFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNewCardNo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewCard)
                    .addComponent(lblConfirmation))
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblNewCard)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUseCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lblRemoveCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoveCard)
                    .addComponent(lblConfirmation))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCardActionPerformed
        String newCard = txtNewCardNo.getText();
        
        loggedInPerson.addCard(newCard);
        
        txtNewCardNo.setText("");
        lblNewCard.setText("Card Added");
        lblConfirmation.setText("");
        lblRemoveCard.setText("");
        
        refresh_cards();
    }//GEN-LAST:event_btnAddCardActionPerformed

    private void btnRemoveCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCardActionPerformed

        loggedInPerson.removeCard(lstCards.getSelectedIndex());
        
        txtNewCardNo.setText("");
        lblRemoveCard.setText("Card Removed");
        lblConfirmation.setText("");
        lblNewCard.setText("");
        
        refresh_cards();
    }//GEN-LAST:event_btnRemoveCardActionPerformed

    private void btnUseCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUseCardActionPerformed
        txtNewCardNo.setText("");
        lblConfirmation.setText("Paid for with card: " + loggedInPerson.get_Cards().get(lstCards.getSelectedIndex()));
        lblNewCard.setText("");
        lblRemoveCard.setText("");
    }//GEN-LAST:event_btnUseCardActionPerformed

    private void btnSaveFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveFirstActionPerformed
        String newCard = txtNewCardNo.getText();
        
        loggedInPerson.addFirstCard(newCard);
        
        txtNewCardNo.setText("");
        lblNewCard.setText("Card Added");
        lblConfirmation.setText("");
        lblRemoveCard.setText("");
        
        refresh_cards();
    }//GEN-LAST:event_btnSaveFirstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Select_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Select_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Select_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Select_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Select_Card(new Person()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCard;
    private javax.swing.JButton btnRemoveCard;
    private javax.swing.JButton btnSaveFirst;
    private javax.swing.JButton btnUseCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConfirmation;
    private javax.swing.JLabel lblNewCard;
    private javax.swing.JLabel lblRemoveCard;
    private javax.swing.JList lstCards;
    private javax.swing.JTextField txtNewCardNo;
    // End of variables declaration//GEN-END:variables
}
